# Generated by Django 5.0 on 2024-01-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newapp',
            new_name='Post',
        ),
    ]
